# Database Connection
spring.datasource.url=jdbc:postgresql://dpg-d81jc7cvikkc73a550g0-a.singapore-postgres.render.com/eventmanager_fomz
spring.datasource.username=eventmanager_fomz_user
spring.datasource.password=psqUnpiW8CgwhK1ooRGRDFKnhVRJqbfK
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
